# Generated by Django 6.0.2 on 2026-02-27 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeCertificate',
            fields=[
                ('administrative_certificate_id', models.AutoField(db_column='administrative_certificate_id', primary_key=True, serialize=False)),
                ('interested_organization', models.CharField(blank=True, db_column='interested_organization', max_length=60, null=True)),
                ('operation', models.CharField(blank=True, db_column='operation', max_length=20, null=True)),
                ('format', models.CharField(blank=True, db_column='format', max_length=8, null=True)),
                ('is_signed_by_warehouse_storage_magaziner', models.BooleanField(db_column='is_signed_by_warehouse_storage_magaziner', default=False)),
                ('is_signed_by_warehouse_storage_accountant', models.BooleanField(db_column='is_signed_by_warehouse_storage_accountant', default=False)),
                ('is_signed_by_warehouse_storage_marketer', models.BooleanField(db_column='is_signed_by_warehouse_storage_marketer', default=False)),
                ('is_signed_by_warehouse_it_chief', models.BooleanField(db_column='is_signed_by_warehouse_it_chief', default=False)),
                ('is_signed_by_warehouse_leader', models.BooleanField(db_column='is_signed_by_warehouse_leader', default=False)),
                ('digital_copy', models.BinaryField(blank=True, db_column='digital_copy', null=True)),
            ],
            options={
                'db_table': 'administrative_certificate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(db_column='asset_id', primary_key=True, serialize=False)),
                ('asset_serial_number', models.CharField(blank=True, db_column='asset_serial_number', max_length=48, null=True)),
                ('asset_inventory_number', models.CharField(blank=True, db_column='asset_inventory_number', max_length=6, null=True)),
                ('asset_name', models.CharField(blank=True, db_column='asset_name', max_length=48, null=True)),
                ('asset_status', models.CharField(blank=True, db_column='asset_status', max_length=30, null=True)),
                ('asset_service_tag', models.CharField(blank=True, db_column='asset_service_tag', max_length=24, null=True)),
            ],
            options={
                'db_table': 'asset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetAttributeDefinition',
            fields=[
                ('asset_attribute_definition_id', models.AutoField(db_column='asset_attribute_definition_id', primary_key=True, serialize=False)),
                ('data_type', models.CharField(blank=True, db_column='data_type', max_length=18, null=True)),
                ('unit', models.CharField(blank=True, db_column='unit', max_length=24, null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=256, null=True)),
            ],
            options={
                'db_table': 'asset_attribute_definition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetBrand',
            fields=[
                ('asset_brand_id', models.AutoField(db_column='asset_brand_id', primary_key=True, serialize=False)),
                ('brand_name', models.CharField(db_column='brand_name', max_length=48)),
                ('brand_code', models.CharField(db_column='brand_code', max_length=16)),
                ('is_active', models.BooleanField(db_column='is_active')),
                ('brand_photo', models.CharField(blank=True, db_column='brand_photo', max_length=512, null=True)),
            ],
            options={
                'db_table': 'asset_brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetConditionHistory',
            fields=[
                ('asset_condition_history_id', models.IntegerField(db_column='asset_condition_history_id', primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, db_column='notes', max_length=256, null=True)),
                ('cosmetic_issues', models.CharField(blank=True, db_column='cosmetic_issues', max_length=128, null=True)),
                ('functional_issues', models.CharField(blank=True, db_column='functional_issues', max_length=128, null=True)),
                ('recommendation', models.CharField(blank=True, db_column='recommendation', max_length=128, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='created_at', null=True)),
            ],
            options={
                'db_table': 'asset_condition_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetIsAssignedToPerson',
            fields=[
                ('assignment_id', models.AutoField(db_column='assignment_id', primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(db_column='start_datetime')),
                ('end_datetime', models.DateTimeField(blank=True, db_column='end_datetime', null=True)),
                ('condition_on_assignment', models.CharField(db_column='condition_on_assignment', max_length=48)),
                ('is_active', models.BooleanField(db_column='is_active')),
            ],
            options={
                'db_table': 'asset_is_assigned_to_person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetIsComposedOfConsumableHistory',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(blank=True, db_column='start_datetime', null=True)),
                ('end_datetime', models.DateTimeField(blank=True, db_column='end_datetime', null=True)),
            ],
            options={
                'db_table': 'asset_is_composed_of_consumable_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetIsComposedOfStockItemHistory',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(blank=True, db_column='start_datetime', null=True)),
                ('end_datetime', models.DateTimeField(blank=True, db_column='end_datetime', null=True)),
            ],
            options={
                'db_table': 'asset_is_composed_of_stock_item_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetModel',
            fields=[
                ('asset_model_id', models.AutoField(db_column='asset_model_id', primary_key=True, serialize=False)),
                ('model_name', models.CharField(blank=True, db_column='model_name', max_length=48, null=True)),
                ('model_code', models.CharField(blank=True, db_column='model_code', max_length=16, null=True)),
                ('release_year', models.IntegerField(blank=True, db_column='release_year', null=True)),
                ('discontinued_year', models.IntegerField(blank=True, db_column='discontinued_year', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('notes', models.CharField(blank=True, db_column='notes', max_length=256, null=True)),
                ('warranty_expiry_in_months', models.IntegerField(blank=True, db_column='warranty_expiry_in_months', null=True)),
            ],
            options={
                'db_table': 'asset_model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetModelDefaultConsumable',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='quantity', default=1)),
                ('notes', models.CharField(blank=True, db_column='notes', max_length=256, null=True)),
            ],
            options={
                'db_table': 'asset_model_default_consumable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetModelDefaultStockItem',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='quantity', default=1)),
                ('notes', models.CharField(blank=True, db_column='notes', max_length=256, null=True)),
            ],
            options={
                'db_table': 'asset_model_default_stock_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetMovement',
            fields=[
                ('asset_movement_id', models.IntegerField(db_column='asset_movement_id', primary_key=True, serialize=False)),
                ('external_maintenance_step_id', models.IntegerField(blank=True, db_column='external_maintenance_step_id', null=True)),
                ('movement_reason', models.CharField(db_column='movement_reason', max_length=128)),
                ('movement_datetime', models.DateTimeField(db_column='movement_datetime')),
            ],
            options={
                'db_table': 'asset_movement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('asset_type_id', models.AutoField(db_column='asset_type_id', primary_key=True, serialize=False)),
                ('asset_type_label', models.CharField(db_column='asset_type_label', max_length=60)),
                ('asset_type_code', models.CharField(db_column='asset_type_code', max_length=18)),
            ],
            options={
                'db_table': 'asset_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttributionOrder',
            fields=[
                ('attribution_order_id', models.AutoField(db_column='attribution_order_id', primary_key=True, serialize=False)),
                ('attribution_order_full_code', models.CharField(blank=True, db_column='attribution_order_full_code', max_length=48, null=True)),
                ('attribution_order_date', models.DateField(blank=True, db_column='attribution_order_date', null=True)),
                ('is_signed_by_central_chief', models.BooleanField(db_column='is_signed_by_central_chief', default=False)),
                ('attribution_order_barcode', models.CharField(blank=True, db_column='attribution_order_barcode', max_length=24, null=True)),
            ],
            options={
                'db_table': 'attribution_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyAssetRequest',
            fields=[
                ('company_asset_request_id', models.IntegerField(db_column='company_asset_request_id', primary_key=True, serialize=False)),
                ('is_signed_by_company', models.BooleanField(blank=True, db_column='is_signed_by_company', null=True)),
                ('administrative_serial_number', models.CharField(blank=True, db_column='administrative_serial_number', max_length=18, null=True)),
                ('title_of_demand', models.CharField(blank=True, db_column='title_of_demand', max_length=255, null=True)),
                ('organization_body_designation', models.CharField(blank=True, db_column='organization_body_designation', max_length=255, null=True)),
                ('register_number_or_book_journal_of_corpse', models.CharField(blank=True, db_column='register_number_or_book_journal_of_corpse', max_length=255, null=True)),
                ('register_number_or_book_journal_of_establishment', models.CharField(blank=True, db_column='register_number_or_book_journal_of_establishment', max_length=255, null=True)),
                ('is_signed_by_company_leader', models.BooleanField(blank=True, db_column='is_signed_by_company_leader', null=True)),
                ('is_signed_by_regional_provider', models.BooleanField(blank=True, db_column='is_signed_by_regional_provider', null=True)),
                ('is_signed_by_company_representative', models.BooleanField(blank=True, db_column='is_signed_by_company_representative', null=True)),
                ('digital_copy', models.BinaryField(blank=True, db_column='digital_copy', null=True)),
            ],
            options={
                'db_table': 'company_asset_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('consumable_id', models.AutoField(db_column='consumable_id', primary_key=True, serialize=False)),
                ('consumable_serial_number', models.CharField(blank=True, db_column='consumable_serial_number', max_length=48, null=True)),
                ('consumable_inventory_number', models.CharField(blank=True, db_column='consumable_inventory_number', max_length=6, null=True)),
                ('consumable_name', models.CharField(blank=True, db_column='consumable_name', max_length=48, null=True)),
                ('consumable_status', models.CharField(blank=True, db_column='consumable_status', max_length=30, null=True)),
            ],
            options={
                'db_table': 'consumable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumableAttributeDefinition',
            fields=[
                ('consumable_attribute_definition_id', models.AutoField(db_column='consumable_attribute_definition_id', primary_key=True, serialize=False)),
                ('data_type', models.CharField(blank=True, db_column='data_type', max_length=18, null=True)),
                ('unit', models.CharField(blank=True, db_column='unit', max_length=24, null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=256, null=True)),
            ],
            options={
                'db_table': 'consumable_attribute_definition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumableBrand',
            fields=[
                ('consumable_brand_id', models.AutoField(db_column='consumable_brand_id', primary_key=True, serialize=False)),
                ('brand_name', models.CharField(db_column='brand_name', max_length=48)),
                ('brand_code', models.CharField(db_column='brand_code', max_length=16)),
                ('is_active', models.BooleanField(db_column='is_active')),
                ('brand_photo', models.CharField(blank=True, db_column='brand_photo', max_length=512, null=True)),
            ],
            options={
                'db_table': 'consumable_brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumableIsAssignedToPerson',
            fields=[
                ('assignment_id', models.AutoField(db_column='assignment_id', primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(db_column='start_datetime')),
                ('end_datetime', models.DateTimeField(blank=True, db_column='end_datetime', null=True)),
                ('condition_on_assignment', models.CharField(db_column='condition_on_assignment', max_length=48)),
                ('is_active', models.BooleanField(db_column='is_active')),
            ],
            options={
                'db_table': 'consumable_is_assigned_to_person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumableModel',
            fields=[
                ('consumable_model_id', models.AutoField(db_column='consumable_model_id', primary_key=True, serialize=False)),
                ('model_name', models.CharField(blank=True, db_column='model_name', max_length=48, null=True)),
                ('model_code', models.CharField(blank=True, db_column='model_code', max_length=16, null=True)),
                ('release_year', models.IntegerField(blank=True, db_column='release_year', null=True)),
                ('discontinued_year', models.IntegerField(blank=True, db_column='discontinued_year', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('notes', models.CharField(blank=True, db_column='notes', max_length=256, null=True)),
                ('warranty_expiry_in_months', models.IntegerField(blank=True, db_column='warranty_expiry_in_months', null=True)),
            ],
            options={
                'db_table': 'consumable_model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumableIsUsedInStockItemHistory',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(blank=True, db_column='start_datetime', null=True)),
                ('end_datetime', models.DateTimeField(blank=True, db_column='end_datetime', null=True)),
            ],
            options={
                'db_table': 'consumable_is_used_in_stock_item_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumableMovement',
            fields=[
                ('consumable_movement_id', models.IntegerField(db_column='consumable_movement_id', primary_key=True, serialize=False)),
                ('external_maintenance_step_id', models.IntegerField(blank=True, db_column='external_maintenance_step_id', null=True)),
                ('movement_reason', models.CharField(db_column='movement_reason', max_length=128)),
                ('movement_datetime', models.DateTimeField(db_column='movement_datetime')),
            ],
            options={
                'db_table': 'consumable_movement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumableType',
            fields=[
                ('consumable_type_id', models.AutoField(db_column='consumable_type_id', primary_key=True, serialize=False)),
                ('consumable_type_label', models.CharField(db_column='consumable_type_label', max_length=60)),
                ('consumable_type_code', models.CharField(db_column='consumable_type_code', max_length=18)),
            ],
            options={
                'db_table': 'consumable_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalMaintenance',
            fields=[
                ('external_maintenance_id', models.IntegerField(db_column='external_maintenance_id', primary_key=True, serialize=False)),
                ('external_maintenance_status', models.CharField(blank=True, db_column='external_maintenance_status', max_length=32, null=True)),
                ('item_received_by_maintenance_provider_datetime', models.DateTimeField(blank=True, db_column='item_received_by_maintenance_provider_datetime', null=True)),
                ('item_sent_to_company_datetime', models.DateTimeField(blank=True, db_column='item_sent_to_company_datetime', null=True)),
                ('item_sent_to_external_maintenance_datetime', models.DateTimeField(blank=True, db_column='item_sent_to_external_maintenance_datetime', null=True)),
                ('item_received_by_company_datetime', models.DateTimeField(blank=True, db_column='item_received_by_company_datetime', null=True)),
            ],
            options={
                'db_table': 'external_maintenance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalMaintenanceDocument',
            fields=[
                ('external_maintenance_document_id', models.IntegerField(db_column='external_maintenance_document_id', primary_key=True, serialize=False)),
                ('document_is_signed', models.BooleanField(blank=True, db_column='document_is_signed', null=True)),
                ('item_is_received_by_maintenance_provider', models.BooleanField(blank=True, db_column='item_is_received_by_maintenance_provider', null=True)),
                ('maintenance_provider_final_decision', models.CharField(blank=True, db_column='maintenance_provider_final_decision', max_length=60, null=True)),
                ('digital_copy', models.BinaryField(blank=True, db_column='digital_copy', null=True)),
            ],
            options={
                'db_table': 'external_maintenance_document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalMaintenanceProvider',
            fields=[
                ('external_maintenance_provider_id', models.IntegerField(db_column='external_maintenance_provider_id', primary_key=True, serialize=False)),
                ('external_maintenance_provider_name', models.CharField(blank=True, db_column='external_maintenance_provider_name', max_length=48, null=True)),
                ('external_maintenance_provider_location', models.CharField(blank=True, db_column='external_maintenance_provider_location', max_length=128, null=True)),
            ],
            options={
                'db_table': 'external_maintenance_provider',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalMaintenanceStep',
            fields=[
                ('external_maintenance_step_id', models.IntegerField(db_column='external_maintenance_step_id', primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(blank=True, db_column='start_datetime', null=True)),
                ('end_datetime', models.DateTimeField(blank=True, db_column='end_datetime', null=True)),
                ('is_successful', models.BooleanField(blank=True, db_column='is_successful', null=True)),
            ],
            options={
                'db_table': 'external_maintenance_step',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalMaintenanceTypicalStep',
            fields=[
                ('external_maintenance_typical_step_id', models.IntegerField(db_column='external_maintenance_typical_step_id', primary_key=True, serialize=False)),
                ('estimated_cost', models.DecimalField(blank=True, db_column='estimated_cost', decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, db_column='actual_cost', decimal_places=2, max_digits=10, null=True)),
                ('maintenance_type', models.CharField(blank=True, db_column='maintenance_type', max_length=8, null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=256, null=True)),
            ],
            options={
                'db_table': 'external_maintenance_typical_step',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('maintenance_id', models.IntegerField(db_column='maintenance_id', primary_key=True, serialize=False)),
                ('is_approved_by_maintenance_chief', models.BooleanField(blank=True, db_column='is_approved_by_maintenance_chief', null=True)),
                ('maintenance_status', models.CharField(blank=True, db_column='maintenance_status', max_length=20, null=True)),
                ('start_datetime', models.DateTimeField(blank=True, db_column='start_datetime', null=True)),
                ('end_datetime', models.DateTimeField(blank=True, db_column='end_datetime', null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=256, null=True)),
                ('is_successful', models.BooleanField(blank=True, db_column='is_successful', null=True)),
                ('digital_copy', models.BinaryField(blank=True, db_column='digital_copy', null=True)),
            ],
            options={
                'db_table': 'maintenance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceStep',
            fields=[
                ('maintenance_step_id', models.IntegerField(db_column='maintenance_step_id', primary_key=True, serialize=False)),
                ('is_successful', models.BooleanField(db_column='is_successful', default=False)),
                ('start_datetime', models.DateTimeField(blank=True, db_column='start_datetime', null=True)),
                ('end_datetime', models.DateTimeField(blank=True, db_column='end_datetime', null=True)),
                ('maintenance_step_status', models.CharField(blank=True, db_column='maintenance_step_status', max_length=60, null=True)),
                ('asset_condition_history', models.IntegerField(blank=True, db_column='asset_condition_history_id', null=True)),
                ('stock_item_condition_history', models.IntegerField(blank=True, db_column='stock_item_condition_history_id', null=True)),
                ('consumable_condition_history', models.IntegerField(blank=True, db_column='consumable_condition_history_id', null=True)),
            ],
            options={
                'db_table': 'maintenance_step',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceStepItemRequest',
            fields=[
                ('maintenance_step_item_request_id', models.IntegerField(db_column='maintenance_step_item_request_id', primary_key=True, serialize=False)),
                ('request_type', models.CharField(db_column='request_type', max_length=24)),
                ('status', models.CharField(db_column='status', max_length=24)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('fulfilled_at', models.DateTimeField(blank=True, db_column='fulfilled_at', null=True)),
                ('rejected_at', models.DateTimeField(blank=True, db_column='rejected_at', null=True)),
                ('note', models.CharField(blank=True, db_column='note', max_length=256, null=True)),
            ],
            options={
                'db_table': 'maintenance_step_item_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTypicalStep',
            fields=[
                ('maintenance_typical_step_id', models.AutoField(db_column='maintenance_typical_step_id', primary_key=True, serialize=False)),
                ('estimated_cost', models.DecimalField(blank=True, db_column='estimated_cost', decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, db_column='actual_cost', decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=256, null=True)),
                ('maintenance_type', models.CharField(blank=True, db_column='maintenance_type', max_length=8, null=True)),
                ('operation_type', models.CharField(blank=True, db_column='operation_type', max_length=24, null=True)),
            ],
            options={
                'db_table': 'maintenance_typical_step',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationalStructure',
            fields=[
                ('organizational_structure_id', models.AutoField(db_column='organizational_structure_id', primary_key=True, serialize=False)),
                ('structure_code', models.CharField(db_column='structure_code', max_length=50)),
                ('structure_name', models.CharField(db_column='structure_name', max_length=255)),
                ('structure_type', models.CharField(db_column='structure_type', max_length=30)),
                ('is_active', models.BooleanField(db_column='is_active')),
            ],
            options={
                'db_table': 'organizational_structure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(db_column='person_id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='first_name', max_length=48)),
                ('last_name', models.CharField(db_column='last_name', max_length=48)),
                ('sex', models.CharField(db_column='sex', max_length=6)),
                ('birth_date', models.DateField(db_column='birth_date')),
                ('is_approved', models.BooleanField(db_column='is_approved', default=False)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonReportsProblemOnAsset',
            fields=[
                ('report_id', models.IntegerField(db_column='report_id', primary_key=True, serialize=False)),
                ('report_datetime', models.DateTimeField(db_column='report_datetime')),
                ('owner_observation', models.CharField(db_column='owner_observation', max_length=256)),
            ],
            options={
                'db_table': 'person_reports_problem_on_asset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonReportsProblemOnConsumable',
            fields=[
                ('report_id', models.IntegerField(db_column='report_id', primary_key=True, serialize=False)),
                ('report_datetime', models.DateTimeField(db_column='report_datetime')),
                ('owner_observation', models.CharField(db_column='owner_observation', max_length=256)),
            ],
            options={
                'db_table': 'person_reports_problem_on_consumable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonReportsProblemOnStockItem',
            fields=[
                ('report_id', models.IntegerField(db_column='report_id', primary_key=True, serialize=False)),
                ('report_datetime', models.DateTimeField(db_column='report_datetime')),
                ('owner_observation', models.CharField(db_column='owner_observation', max_length=256)),
            ],
            options={
                'db_table': 'person_reports_problem_on_stock_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(db_column='role_id', primary_key=True, serialize=False)),
                ('role_code', models.CharField(db_column='role_code', max_length=60)),
                ('role_label', models.CharField(db_column='role_label', max_length=60)),
                ('description', models.CharField(blank=True, db_column='description', max_length=256, null=True)),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhysicalCondition',
            fields=[
                ('condition_id', models.IntegerField(db_column='condition_id', primary_key=True, serialize=False)),
                ('condition_code', models.CharField(blank=True, db_column='condition_code', max_length=12, null=True)),
                ('condition_label', models.CharField(blank=True, db_column='condition_label', max_length=12, null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=256, null=True)),
            ],
            options={
                'db_table': 'physical_condition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(db_column='position_id', primary_key=True, serialize=False)),
                ('position_code', models.CharField(db_column='position_code', max_length=48)),
                ('position_label', models.CharField(db_column='position_label', max_length=60)),
                ('description', models.CharField(blank=True, db_column='description', max_length=256, null=True)),
            ],
            options={
                'db_table': 'position',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReceiptReport',
            fields=[
                ('receipt_report_id', models.AutoField(db_column='receipt_report_id', primary_key=True, serialize=False)),
                ('report_datetime', models.DateTimeField(auto_now_add=True, db_column='report_datetime', null=True)),
                ('report_full_code', models.CharField(blank=True, db_column='report_full_code', max_length=48, null=True)),
                ('digital_copy', models.BinaryField(blank=True, db_column='digital_copy', null=True)),
            ],
            options={
                'db_table': 'receipt_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(db_column='room_id', primary_key=True, serialize=False)),
                ('room_name', models.CharField(db_column='room_name', max_length=30)),
            ],
            options={
                'db_table': 'room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('room_type_id', models.AutoField(db_column='room_type_id', primary_key=True, serialize=False)),
                ('room_type_label', models.CharField(db_column='room_type_label', max_length=60)),
                ('room_type_code', models.CharField(db_column='room_type_code', max_length=18)),
            ],
            options={
                'db_table': 'room_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('stock_item_id', models.AutoField(db_column='stock_item_id', primary_key=True, serialize=False)),
                ('stock_item_inventory_number', models.CharField(blank=True, db_column='stock_item_inventory_number', max_length=6, null=True)),
                ('stock_item_name', models.CharField(blank=True, db_column='stock_item_name', max_length=48, null=True)),
                ('stock_item_status', models.CharField(blank=True, db_column='stock_item_status', max_length=30, null=True)),
            ],
            options={
                'db_table': 'stock_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockItemAttributeDefinition',
            fields=[
                ('stock_item_attribute_definition_id', models.AutoField(db_column='stock_item_attribute_definition_id', primary_key=True, serialize=False)),
                ('data_type', models.CharField(blank=True, db_column='data_type', max_length=18, null=True)),
                ('unit', models.CharField(blank=True, db_column='unit', max_length=24, null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=256, null=True)),
            ],
            options={
                'db_table': 'stock_item_attribute_definition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockItemBrand',
            fields=[
                ('stock_item_brand_id', models.AutoField(db_column='stock_item_brand_id', primary_key=True, serialize=False)),
                ('brand_name', models.CharField(db_column='brand_name', max_length=48)),
                ('brand_code', models.CharField(db_column='brand_code', max_length=16)),
                ('is_active', models.BooleanField(db_column='is_active')),
                ('brand_photo', models.CharField(blank=True, db_column='brand_photo', max_length=512, null=True)),
            ],
            options={
                'db_table': 'stock_item_brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockItemIsAssignedToPerson',
            fields=[
                ('assignment_id', models.AutoField(db_column='assignment_id', primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(db_column='start_datetime')),
                ('end_datetime', models.DateTimeField(blank=True, db_column='end_datetime', null=True)),
                ('condition_on_assignment', models.CharField(db_column='condition_on_assignment', max_length=48)),
                ('is_active', models.BooleanField(db_column='is_active')),
            ],
            options={
                'db_table': 'stock_item_is_assigned_to_person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockItemModel',
            fields=[
                ('stock_item_model_id', models.AutoField(db_column='stock_item_model_id', primary_key=True, serialize=False)),
                ('model_name', models.CharField(blank=True, db_column='model_name', max_length=48, null=True)),
                ('model_code', models.CharField(blank=True, db_column='model_code', max_length=16, null=True)),
                ('release_year', models.IntegerField(blank=True, db_column='release_year', null=True)),
                ('discontinued_year', models.IntegerField(blank=True, db_column='discontinued_year', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('notes', models.CharField(blank=True, db_column='notes', max_length=256, null=True)),
                ('warranty_expiry_in_months', models.IntegerField(blank=True, db_column='warranty_expiry_in_months', null=True)),
            ],
            options={
                'db_table': 'stock_item_model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockItemMovement',
            fields=[
                ('stock_item_movement_id', models.IntegerField(db_column='stock_item_movement_id', primary_key=True, serialize=False)),
                ('external_maintenance_step_id', models.IntegerField(blank=True, db_column='external_maintenance_step_id', null=True)),
                ('movement_reason', models.CharField(db_column='movement_reason', max_length=128)),
                ('movement_datetime', models.DateTimeField(db_column='movement_datetime')),
            ],
            options={
                'db_table': 'stock_item_movement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockItemType',
            fields=[
                ('stock_item_type_id', models.AutoField(db_column='stock_item_type_id', primary_key=True, serialize=False)),
                ('stock_item_type_label', models.CharField(db_column='stock_item_type_label', max_length=60)),
                ('stock_item_type_code', models.CharField(db_column='stock_item_type_code', max_length=18)),
            ],
            options={
                'db_table': 'stock_item_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=20, unique=True)),
                ('password_hash', models.CharField(db_column='password_hash', max_length=512)),
                ('created_at_datetime', models.DateTimeField(db_column='created_at_datetime')),
                ('disabled_at_datetime', models.DateTimeField(blank=True, db_column='disabled_at_datetime', null=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
                ('account_status', models.CharField(db_column='account_status', max_length=24)),
                ('failed_login_attempts', models.IntegerField(db_column='failed_login_attempts', default=0)),
                ('password_last_changed_datetime', models.DateTimeField(db_column='password_last_changed_datetime')),
                ('created_by_user_id', models.IntegerField(blank=True, db_column='created_by_user_id', null=True)),
                ('modified_by_user_id', models.IntegerField(blank=True, db_column='modified_by_user_id', null=True)),
                ('modified_at_datetime', models.DateTimeField(blank=True, db_column='modified_at_datetime', null=True)),
            ],
            options={
                'db_table': 'user_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.AutoField(db_column='warehouse_id', primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(blank=True, db_column='warehouse_name', max_length=60, null=True)),
                ('warehouse_address', models.CharField(blank=True, db_column='warehouse_address', max_length=128, null=True)),
            ],
            options={
                'db_table': 'warehouse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetAttributeValue',
            fields=[
                ('asset_attribute_definition', models.ForeignKey(db_column='asset_attribute_definition_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.assetattributedefinition')),
                ('value_string', models.CharField(blank=True, db_column='value_string', max_length=1024, null=True)),
                ('value_bool', models.BooleanField(blank=True, db_column='value_bool', null=True)),
                ('value_date', models.DateField(blank=True, db_column='value_date', null=True)),
                ('value_number', models.DecimalField(blank=True, db_column='value_number', decimal_places=6, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'asset_attribute_value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetTypeAttribute',
            fields=[
                ('asset_attribute_definition', models.ForeignKey(db_column='asset_attribute_definition_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.assetattributedefinition')),
                ('is_mandatory', models.BooleanField(blank=True, db_column='is_mandatory', null=True)),
                ('default_value', models.CharField(blank=True, db_column='default_value', max_length=255, null=True)),
            ],
            options={
                'db_table': 'asset_type_attribute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetModelAttributeValue',
            fields=[
                ('asset_model', models.ForeignKey(db_column='asset_model_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.assetmodel')),
                ('value_bool', models.BooleanField(blank=True, db_column='value_bool', null=True)),
                ('value_string', models.CharField(blank=True, db_column='value_string', max_length=1024, null=True)),
                ('value_number', models.DecimalField(blank=True, db_column='value_number', decimal_places=6, max_digits=18, null=True)),
                ('value_date', models.DateField(blank=True, db_column='value_date', null=True)),
            ],
            options={
                'db_table': 'asset_model_attribute_value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumableAttributeValue',
            fields=[
                ('consumable_attribute_definition', models.ForeignKey(db_column='consumable_attribute_definition_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.consumableattributedefinition')),
                ('value_string', models.CharField(blank=True, db_column='value_string', max_length=1024, null=True)),
                ('value_bool', models.BooleanField(blank=True, db_column='value_bool', null=True)),
                ('value_date', models.DateField(blank=True, db_column='value_date', null=True)),
                ('value_number', models.DecimalField(blank=True, db_column='value_number', decimal_places=6, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'consumable_attribute_value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumableTypeAttribute',
            fields=[
                ('consumable_attribute_definition', models.ForeignKey(db_column='consumable_attribute_definition_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.consumableattributedefinition')),
                ('is_mandatory', models.BooleanField(blank=True, db_column='is_mandatory', null=True)),
                ('default_value', models.CharField(blank=True, db_column='default_value', max_length=255, null=True)),
            ],
            options={
                'db_table': 'consumable_type_attribute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumableIsCompatibleWithAsset',
            fields=[
                ('consumable_model', models.ForeignKey(db_column='consumable_model_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='api.consumablemodel')),
            ],
            options={
                'db_table': 'consumable_is_compatible_with_asset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumableModelAttributeValue',
            fields=[
                ('consumable_model', models.ForeignKey(db_column='consumable_model_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.consumablemodel')),
                ('value_bool', models.BooleanField(blank=True, db_column='value_bool', null=True)),
                ('value_string', models.CharField(blank=True, db_column='value_string', max_length=1024, null=True)),
                ('value_number', models.DecimalField(blank=True, db_column='value_number', decimal_places=6, max_digits=18, null=True)),
                ('value_date', models.DateField(blank=True, db_column='value_date', null=True)),
            ],
            options={
                'db_table': 'consumable_model_attribute_value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationalStructureRelation',
            fields=[
                ('organizational_structure', models.ForeignKey(db_column='organizational_structure_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='child_relations', serialize=False, to='api.organizationalstructure')),
                ('relation_id', models.IntegerField(blank=True, db_column='relation_id', null=True)),
                ('relation_type', models.CharField(blank=True, db_column='relation_type', max_length=60, null=True)),
            ],
            options={
                'db_table': 'organizational_structure_relation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonRoleMapping',
            fields=[
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.role')),
            ],
            options={
                'db_table': 'person_role_mapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockItemAttributeValue',
            fields=[
                ('stock_item_attribute_definition', models.ForeignKey(db_column='stock_item_attribute_definition_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.stockitemattributedefinition')),
                ('value_string', models.CharField(blank=True, db_column='value_string', max_length=1024, null=True)),
                ('value_bool', models.BooleanField(blank=True, db_column='value_bool', null=True)),
                ('value_date', models.DateField(blank=True, db_column='value_date', null=True)),
                ('value_number', models.DecimalField(blank=True, db_column='value_number', decimal_places=6, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'stock_item_attribute_value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockItemTypeAttribute',
            fields=[
                ('stock_item_attribute_definition', models.ForeignKey(db_column='stock_item_attribute_definition_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.stockitemattributedefinition')),
                ('is_mandatory', models.BooleanField(blank=True, db_column='is_mandatory', null=True)),
                ('default_value', models.CharField(blank=True, db_column='default_value', max_length=255, null=True)),
            ],
            options={
                'db_table': 'stock_item_type_attribute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockItemIsCompatibleWithAsset',
            fields=[
                ('stock_item_model', models.ForeignKey(db_column='stock_item_model_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='api.stockitemmodel')),
            ],
            options={
                'db_table': 'stock_item_is_compatible_with_asset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockItemModelAttributeValue',
            fields=[
                ('stock_item_model', models.ForeignKey(db_column='stock_item_model_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.stockitemmodel')),
                ('value_bool', models.BooleanField(blank=True, db_column='value_bool', null=True)),
                ('value_string', models.CharField(blank=True, db_column='value_string', max_length=1024, null=True)),
                ('value_number', models.DecimalField(blank=True, db_column='value_number', decimal_places=6, max_digits=18, null=True)),
                ('value_date', models.DateField(blank=True, db_column='value_date', null=True)),
            ],
            options={
                'db_table': 'stock_item_model_attribute_value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceStepAttributeChange',
            fields=[
                ('maintenance_step_attribute_change_id', models.BigAutoField(db_column='maintenance_step_attribute_change_id', primary_key=True, serialize=False)),
                ('target_type', models.CharField(db_column='target_type', max_length=20)),
                ('target_id', models.IntegerField(blank=True, db_column='target_id', null=True)),
                ('attribute_definition_id', models.IntegerField(db_column='attribute_definition_id')),
                ('value_string', models.CharField(blank=True, db_column='value_string', max_length=1024, null=True)),
                ('value_bool', models.BooleanField(blank=True, db_column='value_bool', null=True)),
                ('value_date', models.DateField(blank=True, db_column='value_date', null=True)),
                ('value_number', models.DecimalField(blank=True, db_column='value_number', decimal_places=6, max_digits=18, null=True)),
                ('created_at_datetime', models.DateTimeField(auto_now_add=True, db_column='created_at_datetime')),
                ('created_by_user_id', models.IntegerField(blank=True, db_column='created_by_user_id', null=True)),
                ('applied_at_datetime', models.DateTimeField(blank=True, db_column='applied_at_datetime', null=True)),
                ('maintenance_step', models.ForeignKey(db_column='maintenance_step_id', on_delete=django.db.models.deletion.CASCADE, related_name='attribute_changes', to='api.maintenancestep')),
            ],
            options={
                'db_table': 'maintenance_step_attribute_change',
            },
        ),
    ]
