# Generated by Django 6.0.3 on 2026-03-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_room_to_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(db_column='location_id', primary_key=True, serialize=False)),
                ('location_name', models.CharField(db_column='location_name', max_length=30)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('location_type_id', models.AutoField(db_column='location_type_id', primary_key=True, serialize=False)),
                ('location_type_label', models.CharField(db_column='location_type_label', max_length=60)),
                ('location_type_code', models.CharField(db_column='location_type_code', max_length=18)),
            ],
            options={
                'db_table': 'location_type',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
