# Generated by Django 6.0.3 on 2026-03-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_room_type_to_location_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.AlterModelOptions(
            name='locationtype',
            options={},
        ),
    ]
