# Generated by Django 6.0.3 on 2026-03-11 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_admin_cert_items_moved_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.ForeignKey(blank=True, db_column='location_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.locationtype'),
        ),
    ]
