# Generated by Django 6.0.3 on 2026-03-11 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_location_location_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetbrand',
            name='brand_photo',
        ),
        migrations.RemoveField(
            model_name='consumablebrand',
            name='brand_photo',
        ),
        migrations.RemoveField(
            model_name='stockitembrand',
            name='brand_photo',
        ),
    ]
