# Generated by Django 6.0.2 on 2026-04-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_i18n_translation_tables'),
        ('api', '0026_location_relation'),
    ]

    operations = [
    ]
