# Generated by Django 6.0.2 on 2026-04-26 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_condition_on_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeCertificateTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('interested_organization', models.CharField(blank=True, db_column='interested_organization', max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'administrative_certificate_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetAttributeDefinitionTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('description', models.CharField(db_column='description', max_length=256)),
                ('unit', models.CharField(blank=True, db_column='unit', max_length=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'asset_attribute_definition_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetConditionHistoryTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('notes', models.CharField(blank=True, db_column='notes', max_length=256, null=True)),
                ('cosmetic_issues', models.CharField(blank=True, db_column='cosmetic_issues', max_length=128, null=True)),
                ('functional_issues', models.CharField(blank=True, db_column='functional_issues', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'asset_condition_history_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetIncidentReport',
            fields=[
                ('asset_incident_report_id', models.IntegerField(db_column='asset_incident_report_id', primary_key=True, serialize=False)),
                ('reason', models.CharField(db_column='reason', max_length=32)),
                ('owner_note', models.TextField(blank=True, db_column='owner_note', null=True)),
                ('digital_copy', models.TextField(blank=True, db_column='digital_copy', null=True)),
                ('is_signed_by_owner', models.BooleanField(db_column='is_signed_by_owner', default=False)),
                ('is_signed_by_it_bureau_chief', models.BooleanField(db_column='is_signed_by_it_bureau_chief', default=False)),
                ('is_signed_by_exploitation_chief', models.BooleanField(db_column='is_signed_by_exploitation_chief', default=False)),
                ('is_signed_by_protection_and_security_bureau_chief', models.BooleanField(db_column='is_signed_by_protection_and_security_bureau_chief', default=False)),
                ('is_signed_by_school_headquarter', models.BooleanField(db_column='is_signed_by_school_headquarter', default=False)),
                ('it_bureau_chief_note', models.TextField(blank=True, db_column='it_bureau_chief_note', null=True)),
                ('exploitation_chief_note', models.TextField(blank=True, db_column='exploitation_chief_note', null=True)),
                ('protection_and_security_bureau_chief_note', models.TextField(blank=True, db_column='protection_and_security_bureau_chief_note', null=True)),
                ('school_headquarter_note', models.TextField(blank=True, db_column='school_headquarter_note', null=True)),
                ('report_datetime', models.DateTimeField(blank=True, db_column='report_datetime', null=True)),
                ('status', models.CharField(blank=True, db_column='status', max_length=20, null=True)),
            ],
            options={
                'db_table': 'asset_incident_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetIncidentReportConsumable',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'asset_incident_report_consumable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetIncidentReportStockItem',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'asset_incident_report_stock_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetIncidentReportTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('reason', models.CharField(blank=True, db_column='reason', max_length=32, null=True)),
                ('status', models.CharField(blank=True, db_column='status', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'asset_incident_report_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetModelTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('model_name', models.CharField(blank=True, db_column='model_name', max_length=48, null=True)),
                ('notes', models.CharField(blank=True, db_column='notes', max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'asset_model_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetMovementTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('movement_reason', models.CharField(db_column='movement_reason', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'asset_movement_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('asset_name', models.CharField(blank=True, db_column='asset_name', max_length=48, null=True)),
                ('asset_name_in_the_administrative_certificate', models.CharField(blank=True, db_column='asset_name_in_the_administrative_certificate', max_length=48, null=True)),
                ('asset_status', models.CharField(blank=True, db_column='asset_status', max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'asset_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthenticationLog',
            fields=[
                ('log_id', models.AutoField(db_column='log_id', primary_key=True, serialize=False)),
                ('attempted_username', models.CharField(blank=True, db_column='attempted_username', max_length=50, null=True)),
                ('event_type', models.CharField(blank=True, db_column='event_type', max_length=24, null=True)),
                ('ip_address', models.CharField(blank=True, db_column='ip_address', max_length=45, null=True)),
                ('event_timestamp', models.DateTimeField(blank=True, db_column='event_timestamp', null=True)),
                ('failure_reason', models.CharField(blank=True, db_column='failure_reason', max_length=60, null=True)),
            ],
            options={
                'db_table': 'authentication_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyAssetRequestTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('title_of_demand', models.CharField(blank=True, db_column='title_of_demand', max_length=24, null=True)),
                ('organization_body_designation', models.CharField(blank=True, db_column='organization_body_designation', max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'company_asset_request_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumableAttributeDefinitionTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('description', models.CharField(db_column='description', max_length=256)),
                ('unit', models.CharField(blank=True, db_column='unit', max_length=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'consumable_attribute_definition_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumableConditionHistory',
            fields=[
                ('consumable_condition_history_id', models.IntegerField(db_column='consumable_condition_history_id', primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, db_column='notes', max_length=256, null=True)),
                ('cosmetic_issues', models.CharField(blank=True, db_column='cosmetic_issues', max_length=128, null=True)),
                ('functional_issues', models.CharField(blank=True, db_column='functional_issues', max_length=128, null=True)),
                ('recommendation', models.CharField(blank=True, db_column='recommendation', max_length=128, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='created_at', null=True)),
            ],
            options={
                'db_table': 'consumable_condition_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumableConditionHistoryTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('notes', models.CharField(blank=True, db_column='notes', max_length=256, null=True)),
                ('cosmetic_issues', models.CharField(blank=True, db_column='cosmetic_issues', max_length=128, null=True)),
                ('functional_issues', models.CharField(blank=True, db_column='functional_issues', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'consumable_condition_history_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumableModelTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('model_name', models.CharField(blank=True, db_column='model_name', max_length=48, null=True)),
                ('notes', models.CharField(blank=True, db_column='notes', max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'consumable_model_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumableMovementTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('movement_reason', models.CharField(db_column='movement_reason', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'consumable_movement_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumableTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('consumable_name', models.CharField(blank=True, db_column='consumable_name', max_length=48, null=True)),
                ('consumable_name_in_administrative_certificate', models.CharField(blank=True, db_column='consumable_name_in_administrative_certificate', max_length=48, null=True)),
                ('consumable_status', models.CharField(blank=True, db_column='consumable_status', max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'consumable_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalMaintenanceDocumentTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('maintenance_provider_final_decision', models.CharField(blank=True, db_column='maintenance_provider_final_decision', max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'external_maintenance_document_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('location_name', models.CharField(db_column='location_name', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'location_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceStepItemRequestTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('note', models.CharField(blank=True, db_column='note', max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'maintenance_step_item_request_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('description', models.CharField(db_column='description', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'maintenance_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationalStructureTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('structure_name', models.CharField(db_column='structure_name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'organizational_structure_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonAssignment',
            fields=[
                ('assignment_id', models.AutoField(db_column='assignment_id', primary_key=True, serialize=False)),
                ('assignment_start_date', models.DateField(blank=True, db_column='assignment_start_date', null=True)),
                ('assignment_end_date', models.DateField(blank=True, db_column='assignment_end_date', null=True)),
                ('employment_type', models.CharField(blank=True, db_column='employment_type', max_length=48, null=True)),
            ],
            options={
                'db_table': 'person_assignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonReportsProblemOnAssetTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('owner_observation', models.CharField(db_column='owner_observation', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'person_reports_problem_on_asset_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonReportsProblemOnConsumableTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('owner_observation', models.CharField(db_column='owner_observation', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'person_reports_problem_on_consumable_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonReportsProblemOnStockItemTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('owner_observation', models.CharField(db_column='owner_observation', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'person_reports_problem_on_stock_item_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('first_name', models.CharField(db_column='first_name', max_length=48)),
                ('last_name', models.CharField(db_column='last_name', max_length=48)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'person_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PositionRoleMapping',
            fields=[
                ('position', models.ForeignKey(db_column='position_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.position')),
                ('created_at', models.DateTimeField(db_column='created_at')),
            ],
            options={
                'db_table': 'position_role_mapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockItemAttributeDefinitionTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('description', models.CharField(db_column='description', max_length=256)),
                ('unit', models.CharField(blank=True, db_column='unit', max_length=24, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'stock_item_attribute_definition_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockItemConditionHistory',
            fields=[
                ('stock_item_condition_history_id', models.IntegerField(db_column='stock_item_condition_history_id', primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, db_column='notes', max_length=256, null=True)),
                ('cosmetic_issues', models.CharField(blank=True, db_column='cosmetic_issues', max_length=128, null=True)),
                ('functional_issues', models.CharField(blank=True, db_column='functional_issues', max_length=128, null=True)),
                ('recommendation', models.CharField(blank=True, db_column='recommendation', max_length=128, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='created_at', null=True)),
            ],
            options={
                'db_table': 'stock_item_condition_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockItemConditionHistoryTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('notes', models.CharField(blank=True, db_column='notes', max_length=256, null=True)),
                ('cosmetic_issues', models.CharField(blank=True, db_column='cosmetic_issues', max_length=128, null=True)),
                ('functional_issues', models.CharField(blank=True, db_column='functional_issues', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'stock_item_condition_history_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockItemModelTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('model_name', models.CharField(blank=True, db_column='model_name', max_length=48, null=True)),
                ('notes', models.CharField(blank=True, db_column='notes', max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'stock_item_model_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockItemMovementTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('movement_reason', models.CharField(db_column='movement_reason', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'stock_item_movement_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockItemTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('stock_item_name', models.CharField(blank=True, db_column='stock_item_name', max_length=48, null=True)),
                ('stock_item_name_in_administrative_certificate', models.CharField(blank=True, db_column='stock_item_name_in_administrative_certificate', max_length=48, null=True)),
                ('stock_item_status', models.CharField(blank=True, db_column='stock_item_status', max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'stock_item_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(db_column='supplier_id', primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(db_column='supplier_name', max_length=60)),
                ('supplier_address', models.CharField(blank=True, db_column='supplier_address', max_length=128, null=True)),
            ],
            options={
                'db_table': 'supplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('supplier_name', models.CharField(db_column='supplier_name', max_length=60)),
                ('supplier_address', models.CharField(blank=True, db_column='supplier_address', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'supplier_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('session_id', models.AutoField(db_column='session_id', primary_key=True, serialize=False)),
                ('ip_address', models.CharField(db_column='ip_address', max_length=45)),
                ('user_agent', models.CharField(blank=True, db_column='user_agent', max_length=255, null=True)),
                ('login_datetime', models.DateTimeField(db_column='login_datetime')),
                ('last_activity', models.DateTimeField(db_column='last_activity')),
                ('logout_datetime', models.DateTimeField(blank=True, db_column='logout_datetime', null=True)),
            ],
            options={
                'db_table': 'user_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseTranslation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], db_column='language_code', max_length=5)),
                ('warehouse_name', models.CharField(db_column='warehouse_name', max_length=60)),
                ('warehouse_address', models.CharField(blank=True, db_column='warehouse_address', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'warehouse_translation',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='locationrelation',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='assetisassignedtoperson',
            name='condition_on_assignment',
        ),
        migrations.RemoveField(
            model_name='stockitemisassignedtoperson',
            name='condition_on_assignment',
        ),
        migrations.RemoveField(
            model_name='consumableisassignedtoperson',
            name='condition_on_assignment',
        ),
    ]
